//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by compEditor.rc
//
#define IDS_ERROR_DELDEFCOMP            1
#define IDS_QUESTION_DELCOMP            2
#define IDS_ERROR_OPENCOMP              3
#define IDS_ERROR_COMPEXIST             4
#define IDS_COMPSETUP_SUCCESS           5
#define IDS_COMPSETUP_FAILED            6
#define IDS_ERROR_OPENFILE              7
#define IDS_EXPORT_FINISH               8
#define IDS_QUESTION_PLSETUP            9
#define IDS_ERROR_PLSETUP               10
#define IDS_EXPORT_SELGROUP             11
#define IDS_ERROR_PLEXPORT              12
#define IDS_ERROR_BLUREXIST             13
#define IDS_ERROR_BLURINPUT             14
#define IDS_QUESTION_POLYPHONE          15
#define IDS_IMPORT_FINISH               16
#define IDS_COMPIMPORT_SUCCESS          17
#define IDS_COMPIMPORT_FAILED           18
#define IDS_COMPIMPORT_SUCCESS2         19
#define IDS_COMPEXPORT_FAILED           20
#define IDS_USERDEF_NODATA              21
#define IDS_USERDEF_EXIST               22
#define IDS_USERDEF_INPUTERROR          23
#define IDS_USERDEF_NOTEXIST            24
#define IDS_USERDEF_NOTEXIST2           25
#define IDS_ERROR_FILEEXIST             26
#define IDS_QUESTION_DELUD2             27
#define IDS_ERROR_TEMPFILE              28
#define IDS_ERROR_ICONFORMAT            29
#define IDS_COMPCREATE_NOCOMP           30
#define IDS_COMPCREATE_NOOUTPUT         31
#define IDS_COMPCREATE_COMPEXIST        32
#define IDS_COMPCREATE_COMPEXIST2       33
#define IDS_COMPCREATE_RULE             34
#define IDS_COMPCREATE_CHAR             35
#define IDS_COMPCREATE_SUCCESS          36
#define IDS_COMPCREATE_ERROR            37
#define IDS_COMPCREATE_KEYMAPERR        38
#define IDS_UPDATE_NONEW                39
#define IDS_FORMAT_CIT                  40
#define IDS_FORMAT_TXT                  41
#define IDS_FORMAT_SPL                  42
#define IDS_FORMAT_UD2                  43
#define IDS_FORMAT_BMP                  44
#define IDS_FORMAT_IMAGE                45
#define IDS_GROUP_DATA                  46
#define IDS_GROUP_OTHER                 47
#define IDS_DATA_SPELL                  48
#define IDS_DATA_COMP                   49
#define IDS_DATA_PL                     50
#define IDS_DATA_FLM                    51
#define IDS_DATA_USERDEF                52
#define IDS_OTHER_CONFIG                53
#define IDS_OTHER_COMPEDITOR            54
#define IDS_DATA_SYMBOL                 55
#define IDS_OTHER_ABOUT                 56
#define IDS_EXIT                        57
#define IDS_BLUR_TUNE                   58
#define IDS_BLUR_RHYME                  59
#define IDS_BLUR_FULL                   60
#define IDS_FDT_USERLIB                 61
#define IDS_FDT_WORDRATE                62
#define IDS_FDT_POLYPHONE               63
#define IDS_FDT_BIHUA                   64
#define IDS_TRAY_TIP                    65
#define IDS_KEYMAP_NODATA               66
#define IDS_KEYMAP_TITLE                67
#define IDS_LSTCOL_NAME                 68
#define IDS_LSTCOL_FL_COUNT             69
#define IDS_LSTCOL_EDITOR               70
#define IDS_LSTCOL_MEMO                 71
#define IDS_LSTCOL_COMP_WORDS           72
#define IDS_LSTCOL_COMP_PL              73
#define IDS_LSTCOL_COMP_URL             74
#define IDS_LSTCOL_P_GNAME              75
#define IDS_LSTCOL_P_SIZE               76
#define IDS_LSTCOL_UD_COMP              77
#define IDS_LSTCOL_UD_PHRASE            78
#define IDS_DATA_USERCMD                79
#define IDS_DATA_SCM                    80
#define IDS_PL_SYS                      81
#define IDS_PROG_CREATEINDEX_SHAPE      82
#define IDS_PROG_CREATEINDEX_SPELL      83
#define IDS_REG_SETVALUE                84
#define IDS_REG_DELVALUE                85
#define IDS_REG_OPENKEY                 86
#define IDS_ERROR_UNICODE               87
#define IDS_RATE_MIN                    88
#define IDS_RATE_MAX                    89
#define IDS_DATA_UDICT                  90
#define IDS_KEYMAP_NOURL                91
#define IDS_KEYMAP_NOCHM                92
#define IDS_KM_TWST2                    93
#define IDS_GROUP_COMP                  94
#define IDS_LSTCOL_SYMBOL               95
#define IDS_LSTCOL_SYMBOL_TYPE          96
#define IDS_LSTCOL_SYMBOL_OUTPUT        97
#define IDS_SYMBOL_MODE1                98
#define IDS_SYMBOL_MODE2                99
#define IDS_SYMBOL_MODE3                100
#define IDS_SYMBOL_ERROR                101
#define IDS_COMP_ENCRYPTED              102
#define IDS_PROG_CREATEINDEX_SPELL2     103
#define IDS_USERDEF_OVERFLOW            104
#define IDS_LICENSEWARNING              105
#define IDS_UD_MODIFIED                 106
#define IDS_UD_SAVE                     107
#define IDS_UD_EMPTYCONFIRM             108
#define IDS_EXPORT_SCODE_SUCCESS        109
#define IDS_EXPORT_SCODE_ERROR          110
#define IDS_LSTCOL_SCODEMAP             111
#define IDS_MSCODE_NONE                 112
#define IDS_USERDEF_LONGPHRASE          113
#define IDS_IMPORT_USER_DICT_PROG       114
#define IDS_EXPORT_COMP_FAILED          115
#define IDR_MAINFRAME                   128
#define IDD_TP_COMPEDITOR               155
#define IDD_LICENSE                     189
#define IDC_BROWSE                      1006
#define IDC_SAVE                        1018
#define IDC_IMPORT                      1047
#define IDC_MODIFY                      1048
#define IDC_SAVEFILE                    1049
#define IDC_BROWSEICON                  1050
#define IDC_COMP                        1112
#define IDC_BROWSECOMP                  1113
#define IDC_URL                         1114
#define IDC_EXPORT                      1117
#define IDC_BROWSE_SAVE                 1139
#define IDC_MAKE                        1140
#define IDC_BROWSE_KEYMAP               1141
#define IDC_ADD                         1173
#define IDC_DEL                         1174
#define IDC_DELALL                      1175
#define IDC_BMWND                       1183
#define IDC_COLORTRANS                  1192
#define IDC_COLOR_TEXT                  1193
#define IDC_KEYMAP                      1210
#define IDC_SYMBOL_NOFIRST              1215
#define IDC_ENCRYPT                     1239
#define IDC_YINXINGMA                   1242
#define IDC_LICENSE                     1251
#define IDC_EDIT                        32791
#define IDC_EXTRACT_SCM                 32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
