######################################################################
# Automatically generated by qmake (3.0) ?? 10? 8 21:43:27 2018
######################################################################

TEMPLATE = lib
TARGET = sinstar3_proxy
INCLUDEPATH += . ./include
CONFIG += staticlib

include($$(SOUIPATH)/demo_com.pri)

PRECOMPILED_HEADER = stdafx.h

# Input
HEADERS += sinstarproxy.h

SOURCES += sinstarproxy.cpp
